Repository beta-bv/Zuypr, pull requests merged in 2022-11, with the labels that each got.

#33 Add workflows
  .github/.workflows/build.yaml
  .github/.workflows/test.yaml
Labels: core

#32 Create .gitignore
  .gitignore
Labels: core

#34 fix fuckup
  .github/workflows/build.yaml
  .github/workflows/test.yaml
Labels: bug

#48 init maui project with mvc model
  .gitignore
  Zuypr/Controller/Class1.cs
  Zuypr/Controller/Controller.csproj
  Zuypr/Controller/Platforms/Android/PlatformClass1.cs
  Zuypr/Controller/Platforms/MacCatalyst/PlatformClass1.cs
  Zuypr/Controller/Platforms/Tizen/PlatformClass1.cs
  Zuypr/Controller/Platforms/Windows/PlatformClass1.cs
  Zuypr/Controller/Platforms/iOS/PlatformClass1.cs
  Zuypr/Model/Class1.cs
  Zuypr/Model/Model.csproj
  Zuypr/Model/Platforms/Android/PlatformClass1.cs
  Zuypr/Model/Platforms/MacCatalyst/PlatformClass1.cs
  Zuypr/Model/Platforms/Tizen/PlatformClass1.cs
  Zuypr/Model/Platforms/Windows/PlatformClass1.cs
  Zuypr/Model/Platforms/iOS/PlatformClass1.cs
  Zuypr/View/App.xaml
  Zuypr/View/App.xaml.cs
  Zuypr/View/AppShell.xaml
  Zuypr/View/AppShell.xaml.cs
  Zuypr/View/MainPage.xaml
  Zuypr/View/MainPage.xaml.cs
  Zuypr/View/MauiProgram.cs
  Zuypr/View/Platforms/Android/AndroidManifest.xml
  Zuypr/View/Platforms/Android/MainActivity.cs
  Zuypr/View/Platforms/Android/MainApplication.cs
  Zuypr/View/Platforms/Android/Resources/values/colors.xml
  Zuypr/View/Platforms/MacCatalyst/AppDelegate.cs
  Zuypr/View/Platforms/MacCatalyst/Info.plist
  Zuypr/View/Platforms/MacCatalyst/Program.cs
  Zuypr/View/Platforms/Tizen/Main.cs
  Zuypr/View/Platforms/Tizen/tizen-manifest.xml
  Zuypr/View/Platforms/Windows/App.xaml
  Zuypr/View/Platforms/Windows/App.xaml.cs
  Zuypr/View/Platforms/Windows/Package.appxmanifest
  Zuypr/View/Platforms/Windows/app.manifest
  Zuypr/View/Platforms/iOS/AppDelegate.cs
  Zuypr/View/Platforms/iOS/Info.plist
  Zuypr/View/Platforms/iOS/Program.cs
  Zuypr/View/Properties/launchSettings.json
  Zuypr/View/Resources/AppIcon/appicon.svg
  Zuypr/View/Resources/AppIcon/appiconfg.svg
  Zuypr/View/Resources/Fonts/OpenSans-Regular.ttf
  Zuypr/View/Resources/Fonts/OpenSans-Semibold.ttf
  Zuypr/View/Resources/Images/dotnet_bot.svg
  Zuypr/View/Resources/Raw/AboutAssets.txt
  Zuypr/View/Resources/Splash/splash.svg
  Zuypr/View/Resources/Styles/Colors.xaml
  Zuypr/View/Resources/Styles/Styles.xaml
  Zuypr/View/View.csproj
  Zuypr/View/View.csproj.user
  Zuypr/Zuypr.sln
Labels: core

#51 hehe
  Controller/Class1.cs
  Controller/Controller.csproj
  Controller/Platforms/Android/PlatformClass1.cs
  Controller/Platforms/MacCatalyst/PlatformClass1.cs
  Controller/Platforms/Tizen/PlatformClass1.cs
  Controller/Platforms/Windows/PlatformClass1.cs
  Controller/Platforms/iOS/PlatformClass1.cs
  Model/Class1.cs
  Model/Model.csproj
  Model/Platforms/Android/PlatformClass1.cs
  Model/Platforms/MacCatalyst/PlatformClass1.cs
  Model/Platforms/Tizen/PlatformClass1.cs
  Model/Platforms/Windows/PlatformClass1.cs
  Model/Platforms/iOS/PlatformClass1.cs
  View/App.xaml
  View/App.xaml.cs
  View/AppShell.xaml
  View/AppShell.xaml.cs
  View/MainPage.xaml
  View/MainPage.xaml.cs
  View/MauiProgram.cs
  View/Platforms/Android/AndroidManifest.xml
  View/Platforms/Android/MainActivity.cs
  View/Platforms/Android/MainApplication.cs
  View/Platforms/Android/Resources/values/colors.xml
  View/Platforms/MacCatalyst/AppDelegate.cs
  View/Platforms/MacCatalyst/Info.plist
  View/Platforms/MacCatalyst/Program.cs
  View/Platforms/Tizen/Main.cs
  View/Platforms/Tizen/tizen-manifest.xml
  View/Platforms/Windows/App.xaml
  View/Platforms/Windows/App.xaml.cs
  View/Platforms/Windows/Package.appxmanifest
  View/Platforms/Windows/app.manifest
  View/Platforms/iOS/AppDelegate.cs
  View/Platforms/iOS/Info.plist
  View/Platforms/iOS/Program.cs
  View/Properties/launchSettings.json
  View/Resources/AppIcon/appicon.svg
  View/Resources/AppIcon/appiconfg.svg
  View/Resources/Fonts/OpenSans-Regular.ttf
  View/Resources/Fonts/OpenSans-Semibold.ttf
  View/Resources/Images/dotnet_bot.svg
  View/Resources/Raw/AboutAssets.txt
  View/Resources/Splash/splash.svg
  View/Resources/Styles/Colors.xaml
  View/Resources/Styles/Styles.xaml
  View/View.csproj
  View/View.csproj.user
  Zuypr.sln
Labels: bug, core

#53 add NUnit
  .gitignore
  Test/Properties/AssemblyInfo.cs
  Test/Test.csproj
  Test/Tests.cs
  Test/packages.config
  Zuypr.sln
Labels: core, test

#55 run build & test check on pr as well
  .github/workflows/build.yaml
  .github/workflows/test.yaml
Labels: enhancement

#56 Update Test.csproj
  Test/Test.csproj
Labels: bug, hotfix

#58 Update globals.json
  global.json
Labels: hotfix
